/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MriSideDrawer {
        "open": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLMriSideDrawerElement extends Components.MriSideDrawer, HTMLStencilElement {
    }
    var HTMLMriSideDrawerElement: {
        prototype: HTMLMriSideDrawerElement;
        new (): HTMLMriSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "mri-side-drawer": HTMLMriSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface MriSideDrawer {
        "open"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "mri-side-drawer": MriSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mri-side-drawer": LocalJSX.MriSideDrawer & JSXBase.HTMLAttributes<HTMLMriSideDrawerElement>;
        }
    }
}
